// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAi79ZO9mxwyl0CCFCYdCEP3QIr9QL2q8',
    appId: '1:815793921670:web:d2b5300a77a2269457bb07',
    messagingSenderId: '815793921670',
    projectId: 'geoponica-3799d',
    authDomain: 'geoponica-3799d.firebaseapp.com',
    databaseURL: 'https://geoponica-3799d-default-rtdb.firebaseio.com',
    storageBucket: 'geoponica-3799d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbdENxJDaKrY8pe5TpYgxoH9aBJFe6tAI',
    appId: '1:815793921670:android:b8ce6b5c30a9166157bb07',
    messagingSenderId: '815793921670',
    projectId: 'geoponica-3799d',
    databaseURL: 'https://geoponica-3799d-default-rtdb.firebaseio.com',
    storageBucket: 'geoponica-3799d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExOrVavYcr_XjhTEgJQNlrmhyPvGzNVo',
    appId: '1:815793921670:ios:cf46ce4f8902c20d57bb07',
    messagingSenderId: '815793921670',
    projectId: 'geoponica-3799d',
    databaseURL: 'https://geoponica-3799d-default-rtdb.firebaseio.com',
    storageBucket: 'geoponica-3799d.firebasestorage.app',
    iosBundleId: 'com.example.sdp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExOrVavYcr_XjhTEgJQNlrmhyPvGzNVo',
    appId: '1:815793921670:ios:cf46ce4f8902c20d57bb07',
    messagingSenderId: '815793921670',
    projectId: 'geoponica-3799d',
    databaseURL: 'https://geoponica-3799d-default-rtdb.firebaseio.com',
    storageBucket: 'geoponica-3799d.firebasestorage.app',
    iosBundleId: 'com.example.sdp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAi79ZO9mxwyl0CCFCYdCEP3QIr9QL2q8',
    appId: '1:815793921670:web:d3ee66daa986c2c757bb07',
    messagingSenderId: '815793921670',
    projectId: 'geoponica-3799d',
    authDomain: 'geoponica-3799d.firebaseapp.com',
    databaseURL: 'https://geoponica-3799d-default-rtdb.firebaseio.com',
    storageBucket: 'geoponica-3799d.firebasestorage.app',
  );
}
